// Generated by CoffeeScript 1.4.0
(function() {
  var app, exphbs, express, session;

  express = require('express');

  session = require('cookie-session');

  exphbs = require('express-handlebars');

  app = express();

  app.engine('hbs', exphbs({
    extname: 'hbs',
    defaultLayout: 'index.hbs'
  }));

  app.set('view engine', 'hbs');

  app.use(session({
    secret: 'todotopsecret'
  }));

  app.get('/todo', function(req, res) {
    return res.render('index');
  });

  app.use("/javascripts", express["static"](__dirname + "/javascripts"));

  app.use(function(req, res, next) {
    res.redirect('/todo');
    return next();
  }).listen(8080);

}).call(this);
