// Generated by CoffeeScript 1.4.0
(function() {
  var app, express;

  express = require('express');

  app = express();

  app.use('/', express["static"](__dirname + "/www"));

  app.listen(8080);

}).call(this);
